name: GitHub cicd
on: [push]
jobs:
  test-cicd-gcp:
    name: cicd test
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'bump version')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Build and push image to Google Container Registry
      - name: Setting up
        uses: google-github-actions/setup-gcloud@master
        with:
          version: '286.0.0'
          service_account_key: ${{ secrets.GCP_SA_KEY_JSON }}
          service_account_email: "project2-20@appspot.gserviceaccount.com"
          project_id: ${{ secrets.GCP_PROJECT_ID }}